### ISSUE TITLE
How to describe the (observed or predicted) water level at a junction

### ISSUE THREAD

**Issue by stijnvanhoey** [smart-data-models/dataModel.OpenChannelManagement#3]
According to the specification, the data model provides an option to represent waterinflow and wateroutflow:
- waterInflow[number]: Water flow inserted to the junction
- waterOutflow[number]: Water flow abstracted from the junction or diverted to another source

But is there also an option to represent the 'waterlevel' at a junction? Preferable in meter above the thalweg, although I'm not sure how this should be linked to the 'OpenChannelCurve' model. 

The water level can be both coming from a simulation as well as an observation at the junction. There is a `waterLevel` as part of the 'simulationOutput[array]: Description of the set of results of simulation of the regulation structure.' in the RegulationStructureSimulation specification as `waterAttribute`, but I can't find other usages. Would it be possible to reuse the concept to represent waterLevel at a junction as well?

**Comment by albertoabellagarcia** [comment]
if the meaning is exactly the same fell free to reuse. But if I understand what you mean in the message, looks like it is something different. this was the case a new attibute should be created.

**Comment by stijnvanhoey** [comment]
As far as I understand, the option to add `WaterLevel` as a new property to the 'OpenChannelJunction' specification is a better fit than the 'simulationOutput' setup.  At a junction, a certain waterlevel can be observed (by a device). Should I add a PR?

```
...
    waterLevel:    
      description: 'Water level at the junction'    
      minimum: 0    
      type: number    
      x-ngsi:    
        type: Property    
        units: m  
...
```
